### PR TITLE
Ensure game sorting works for variants that don't have 7 players.

### PR DESCRIPTION
**Pull request by tttppp**
Replace NMembers with a count of the number of spaces left for a game.

This ensures that France vs Austria games aren't always at the bottom of the open list.

For some reason they seem to be always at the bottom of the started list, and at the top of the finished list too, but I don't understand why that is.

### CODE REVIEW

**Comment by tttppp** [comment]
I've no idea how upgrading the db works - I didn't look into that. This will probably break things as it currently is!  I was hoping you could give me some pointers, or finish the change off.

**Comment by zond** [comment]
I like what you're doing, but yeah this will be problematic for the db.

I don't even remember all the problems we're going to have to solve for this change :)

I recommend setting up your own app engine instance for testing, where you:

- deploy
- use the tool to create some games
- try this change

I can tell you that it might be easier to keep NMembers, and just add Spaces. Datastore operations will start creating ignorable errors if fields are removed IIRC.

Suggested migration path:

- add spaces, the correct setting of the field, and a migration function (with a URL so one can call it) that goes through all open games (the only ones with non zero Spaces) and updates them (in transactions) to have correct spaces.
- deploy this and run the migration func.
- change the sorting of the games to use Spaces instead of NMembers, remove indexes.yaml, run all diptests to make sure indexes.yaml contains the actually needed indexes.
- upload the new indexes.yaml to create the new indexes.
- deploy the code using the new indexes.
- vacuum the redundant indexes for price and performance.

**Comment by zond** [comment]
I got thinking about this - it's as bad if 2 player games are always first as if they are always last in the list. What do you think?

**Comment by tttppp** [comment]
They're not *always* first. They are mixed with other games with one seat left. I agree that it's not a perfect system though, it just seemed better than always last. I think the worst part of the issue is that they always seem to be first on the finished list and last in the open games. I couldn't spot any code causing that though.

**Comment by tttppp** [comment]
I'll have another think about this, and maybe close the pull request and create an open issue instead.

**Comment by zond** [comment]
I think always first in finished list was because there were a lot of new FranceVsAustria that just finished?

**Comment by tttppp** [comment]
You're right - they are no longer all first in the finished list.  I'm closing this PR as I no longer think this is the right solution.  I think the right solution involves filtering.

Putting the game with the most signed up players first might start being annoying once we implement [World War IV](http://www.vdiplomacy.com/variants.php?variantID=102) which has 36 player slots.  I doubt this is imminent!

**Comment by zond** [comment]
Sounds good :)

**Pull request closed without merging**
