### PR TITLE
Updated colours

### PR DESCRIPTION
**Pull request by JorenC**
Updated colours. The first 45 are "hand-picked" (although some are already quite similar), the rest is added from the original list (and not specifically checked).

### CODE REVIEW

**Comment by zond** [comment]
I assume @tttppp will look at this?

**Comment by JorenC** [comment]
Would be good :)

**Comment by tttppp** [comment]
Looks good to me.  There are a few colours that end up unfortunately close to each other in Chaos and Twenty Twenty:
image
image

**Comment by tttppp** [comment]
The colour for Portugal is a bit similar to the land colour too.

Anyway - I've merged this and we can always update again later.

**Pull request merged**
