### PR TITLE
Support other maps than classical.

### PR DESCRIPTION
**Pull request by tttppp**

### CODE REVIEW

**Comment by zond** [comment]
Cool, I'll merge this once there's a godip PR that adds only the things
necessary for this to work :)

**Comment by tttppp** [comment]
I wasn't 100% sure about the etag. Your version of go-bindata seemed to add an AssetInfo method containing a timestamp, but mine didn't, so I had to refactor to add a version string. My browsers seemed to ignore the etag anyway - updating the SVG and the version didn't force the browser to skip the cache.

**Comment by zond** [comment]
Browsers are weird. You might create the ETAG from hashing the SVG source?

**Comment by tttppp** [comment]
When searching for versions of go-bindata I came across a pull request that added md5 checksums to the generated file. I think there must be something more fundamental though, because loading the Variant map endpoint gave me the updated map, whereas the ajax call got the old one.

**Comment by zond** [comment]
Yeah, how browsers handle caching parameters has always been a mystery to
me :/

On May 20, 2017 17:58, "tttppp" <notifications@github.com> wrote:

When searching for versions of go-bindata I came across a pull request that
added md5 checksums to the generated file. I think there must be something
more fundamental though, because loading the Variant map endpoint gave me
the updated map, whereas the ajax call got the old one.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zond/diplicity/pull/79#issuecomment-302881795>, or mute
the thread

**Comment by tttppp** [comment]
I read up on this (e.g. [here](http://stackoverflow.com/questions/6350384/http-combining-expiration-and-validation-caching)), and the issue I was seeing is that max-age is more important than the etag.  Consider the following code:
```
	w.Header().Set("Etag", etag)
	w.Header().Set("Cache-Control", "max-age=2592000") // 30 days
```
This is instructing the client to retrieve the response from the cache for 30 days, and then send the etag with the next request. The server will only return the asset if the etag has changed, otherwise it will just return a "304 Not Modified" response along with another "max-age" value. The client shouldn't hit the server again for another 30 days.

It's not anticipated that maps will change much, but I would think we could consider reducing max-age down to the 1 hour-1 day range.  That way it's possible to fix a broken map without significant disruption to games (this is a bit of an edge case).  The relevant code is in diplicity/variants/variants.go if you wanted to change it.

**Comment by zond** [comment]
I'm getting comfortable just accepting your pull requests, so you go ahead?
:)

**Pull request merged**
